using Shared.Models.Base;
using System;

namespace WebStreamr;

public sealed class ModuleConf : BaseSettings, ICloneable
{
    public ModuleConf()
    {
        plugin = "webstreamr";
        displayname = "WebStreamr";
        displayindex = 1060;
        enable = true;
        // This is a public, configurable WebStreamrMBG manifest. Replace it
        // with the manifest URL generated by the add-on configuration page.
        manifest = "https://87d6a6ef6b58-webstreamrmbg.baby-beamup.club/%7B%22multi%22%3A%22on%22%7D/manifest.json";
        // Keep the phone as a byte proxy when the add-on supplies Referer or
        // other request headers. This does not transcode the media.
        streamproxy = true;
    }

    /// <summary>
    /// Configured Stremio manifest URL. It must expose the standard stream
    /// resource and should be an HTTPS URL from a source the user is allowed
    /// to access.
    /// </summary>
    public string manifest { get; set; }

    /// <summary>HTTP timeout for the add-on stream request.</summary>
    public int timeoutSeconds { get; set; } = 25;

    /// <summary>Maximum number of HTTP streams shown for one title.</summary>
    public int maxStreams { get; set; } = 100;

    public ModuleConf Clone()
    {
        return (ModuleConf)MemberwiseClone();
    }

    object ICloneable.Clone()
    {
        return MemberwiseClone();
    }
}

public sealed record WebStreamItem(
    string Url,
    string Name,
    string Title,
    string Quality,
    System.Collections.Generic.List<HeadersModel> Headers
);
