using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Web;

namespace NextHUB;

/// <summary>Vietnamese labels for NextHUB menu/category entries only.</summary>
public static class CategoryVi
{
    static readonly Dictionary<string, string> BySlug = new(StringComparer.OrdinalIgnoreCase)
    {
        [""] = "Mới nhất",
        ["latest"] = "Mới nhất",
        ["new"] = "Mới nhất",
        ["newest"] = "Mới nhất",
        ["trending"] = "Thịnh hành",
        ["popular"] = "Phổ biến",
        ["most-viewed"] = "Xem nhiều nhất",
        ["top-rated"] = "Đánh giá cao",
        ["longest"] = "Video dài",
        ["shortest"] = "Video ngắn",
        ["all"] = "Tất cả",
        ["anal"] = "Hậu môn",
        ["anal-sex"] = "Quan hệ hậu môn",
        ["russian-anal"] = "Hậu môn Nga",
        ["rough-anal"] = "Hậu môn mạnh",
        ["skinny-anal"] = "Hậu môn với người mảnh mai",
        ["anal-mature"] = "Hậu môn với người trưởng thành",
        ["anal-young-girls"] = "Hậu môn với người trẻ",
        ["anal-stockings"] = "Hậu môn với vớ dài",
        ["anal-orgasm"] = "Cực khoái hậu môn",
        ["blowjob"] = "Khẩu giao",
        ["deep-blowjob"] = "Khẩu giao sâu",
        ["footjob"] = "Kích thích bằng chân",
        ["handjob"] = "Kích thích bằng tay",
        ["pussy-licking"] = "Khẩu giao nữ",
        ["rimming-for-girls"] = "Rimming cho nữ",
        ["rimming-for-man"] = "Rimming cho nam",
        ["creampie"] = "Xuất tinh bên trong",
        ["cum-mouth"] = "Xuất tinh vào miệng",
        ["cum-throat"] = "Xuất tinh sâu vào họng",
        ["cum-ass"] = "Xuất tinh lên mông",
        ["cum-tits"] = "Xuất tinh lên ngực",
        ["cum-vagina"] = "Xuất tinh lên vùng kín",
        ["cum-stomach"] = "Xuất tinh lên bụng",
        ["facial"] = "Xuất tinh lên mặt",
        ["squirt"] = "Squirt",
        ["masturbation"] = "Thủ dâm nữ",
        ["jerking"] = "Kích thích bằng tay",
        ["threesome"] = "Quan hệ ba người",
        ["group"] = "Quan hệ nhóm",
        ["rus-orgy"] = "Nhóm sinh viên Nga",
        ["double"] = "Thâm nhập kép",
        ["double-fisting"] = "Fisting kép",
        ["fisting"] = "Fisting",
        ["facesitting"] = "Ngồi lên mặt",
        ["doggystyle"] = "Tư thế từ phía sau",
        ["riding"] = "Tư thế cưỡi",
        ["pov"] = "Góc nhìn thứ nhất",
        ["female-pov"] = "Góc nhìn của nữ",
        ["girls-love"] = "Đồng tính nữ",
        ["lesbians"] = "Đồng tính nữ",
        ["mfm"] = "Hai nam một nữ",
        ["fmf"] = "Hai nữ một nam",
        ["bdsm"] = "BDSM",
        ["bondage"] = "Trói buộc",
        ["forced"] = "Cưỡng ép giả tưởng",
        ["painful-anal"] = "Hậu môn mạnh",
        ["rough"] = "Quan hệ mạnh",
        ["hardcore"] = "Hardcore",
        ["spanking"] = "Đánh mông",
        ["strangers"] = "Người lạ",
        ["incest"] = "Gia đình giả tưởng",
        ["russian-incest"] = "Gia đình Nga giả tưởng",
        ["bro-sis"] = "Anh em giả tưởng",
        ["mother-and-son"] = "Mẹ và con trai giả tưởng",
        ["mother-and-daughter"] = "Mẹ và con gái giả tưởng",
        ["father-and-daughter"] = "Cha và con gái giả tưởng",
        ["teacher"] = "Giáo viên và học sinh",
        ["university"] = "Trường đại học",
        ["hostel"] = "Ký túc xá",
        ["students"] = "Sinh viên",
        ["school"] = "Trường học",
        ["milfs"] = "Phụ nữ trưởng thành",
        ["milfs-rus"] = "Phụ nữ Nga trưởng thành",
        ["mature"] = "Trưởng thành",
        ["young"] = "Người trẻ 18+",
        ["teens"] = "Tuổi 18+",
        ["skinny-teens"] = "Người trẻ mảnh mai 18+",
        ["mini"] = "Nhỏ nhắn",
        ["chubby"] = "Đầy đặn",
        ["skinny"] = "Mảnh mai",
        ["tall-girls"] = "Người cao",
        ["big-tits"] = "Ngực lớn",
        ["small-tits"] = "Ngực nhỏ",
        ["perfect-tits"] = "Ngực đẹp",
        ["natural-tits"] = "Ngực tự nhiên",
        ["big-cocks"] = "Dương vật lớn",
        ["small-cocks"] = "Kích thước nhỏ",
        ["nice-ass"] = "Mông đẹp",
        ["elastic-ass"] = "Mông săn chắc",
        ["big-ass"] = "Mông lớn",
        ["wide-pussy"] = "Vùng kín rộng",
        ["shaved-pussy"] = "Đã cạo",
        ["unshaved"] = "Không cạo",
        ["wet-pussies"] = "Ẩm ướt",
        ["pale"] = "Da sáng",
        ["tattooed"] = "Hình xăm",
        ["redhead"] = "Tóc đỏ",
        ["brunette"] = "Tóc nâu",
        ["blondes"] = "Tóc vàng",
        ["short-hair"] = "Tóc ngắn",
        ["long-hair"] = "Tóc dài",
        ["hair-kare"] = "Tóc bob",
        ["glasses"] = "Đeo kính",
        ["pregnant"] = "Mang thai",
        ["home-porn"] = "Tự quay",
        ["home-rus"] = "Tự quay Nga",
        ["real"] = "Không dàn dựng",
        ["amateur"] = "Nghiệp dư",
        ["webcam"] = "Webcam",
        ["hidden-cam"] = "Camera ẩn",
        ["casting"] = "Thử vai",
        ["massage"] = "Mát-xa",
        ["office"] = "Văn phòng",
        ["kitchen"] = "Nhà bếp",
        ["bathroom"] = "Phòng tắm",
        ["nature"] = "Ngoài trời",
        ["beach"] = "Bãi biển",
        ["hotel"] = "Khách sạn",
        ["gym"] = "Phòng tập",
        ["stockings"] = "Vớ dài",
        ["black-stockings"] = "Vớ đen",
        ["white-stockings"] = "Vớ trắng",
        ["sexy-underwear"] = "Đồ lót",
        ["dressed"] = "Mặc quần áo",
        ["uniform"] = "Đồng phục",
        ["latex"] = "Latex",
        ["cosplay"] = "Hóa trang",
        ["toys"] = "Đồ chơi",
        ["sex-toys"] = "Đồ chơi",
        ["dildo"] = "Dildo",
        ["vibrator"] = "Máy rung",
        ["erotic"] = "Gợi cảm",
        ["erotic-rus"] = "Gợi cảm Nga",
        ["hq-porn"] = "Hình ảnh đẹp",
        ["rus-hq"] = "Nga chất lượng cao",
        ["russian"] = "Nga",
        ["rus"] = "Nga",
        ["norus"] = "Quốc tế",
        ["japanese"] = "Nhật Bản",
        ["asian"] = "Châu Á",
        ["interracial"] = "Khác chủng tộc",
        ["latina"] = "Mỹ Latin",
        ["hentai"] = "Hentai",
        ["cartoon"] = "Hoạt hình",
        ["vintage"] = "Cổ điển",
        ["romantic"] = "Lãng mạn",
        ["funny"] = "Hài hước",
        ["compilation"] = "Tổng hợp",
        ["long-vids"] = "Video dài",
        ["short-vids"] = "Video ngắn",
        ["asmr"] = "ASMR"
    };

    static readonly Dictionary<string, string> Exact = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Все"] = "Tất cả",
        ["Любое"] = "Bất kỳ",
        ["Новинки"] = "Mới nhất",
        ["В тренде"] = "Thịnh hành",
        ["Топ просмотров"] = "Xem nhiều nhất",
        ["Популярное"] = "Phổ biến",
        ["Качество"] = "Chất lượng",
        ["Формат"] = "Định dạng",
        ["Ориентация"] = "Xu hướng",
        ["Сортировка"] = "Sắp xếp",
        ["Выбрать"] = "Chọn"
    };

    public static string Translate(string label, string slug)
    {
        if (Exact.TryGetValue(label?.Trim() ?? string.Empty, out string exact))
            return exact;

        string normalized = HttpUtility.UrlDecode(slug ?? string.Empty)?.Trim().Trim('/').ToLowerInvariant();
        if (string.IsNullOrEmpty(normalized))
            return Exact.TryGetValue(label ?? string.Empty, out exact) ? exact : label;

        normalized = Regex.Replace(normalized, @"^(videos?|categories?)/", string.Empty);
        normalized = Regex.Replace(normalized, @"[?&].*$", string.Empty);

        return BySlug.TryGetValue(normalized, out string translated)
            ? translated
            : label;
    }
}
