using Shared.Models.Base;
using Shared.Models.Templates;
using System;

namespace K20;

public sealed class ModuleConf : BaseSettings, ICloneable
{
    public ModuleConf()
    {
        plugin = "k20";
        displayname = "K20 Phim Việt";
        displayindex = 576;
        enable = true;
        // This is a public, configurable K20 manifest. Replace it
        // with the manifest URL generated by the add-on configuration page.
        manifest = "https://sc.k-20.xyz/eyJtYWluIjpbIm5ndW9uYy1tb3ZpZSIsIm5ndW9uYy1zZXJpZXMiLCJzdHAtbW92aWUiLCJzdHAtc2VyaWVzIiwidnNtb3YtbW92aWUiLCJ2c21vdi1zZXJpZXMiXSwic2hlbHZlcyI6W10sInNob3dUdk9uSG9tZSI6ZmFsc2V9/manifest.json";
        // Keep the phone as a byte proxy when the add-on supplies Referer or
        // other request headers. This does not transcode the media.
        streamproxy = true;
    }

    /// <summary>
    /// Configured Stremio manifest URL. It must expose the standard stream
    /// resource and should be an HTTPS URL from a source the user is allowed
    /// to access.
    /// </summary>
    public string manifest { get; set; }

    /// <summary>HTTP timeout for the add-on stream request.</summary>
    public int timeoutSeconds { get; set; } = 25;

    /// <summary>Maximum number of HTTP streams shown for one title.</summary>
    public int maxStreams { get; set; } = 100;

    public ModuleConf Clone()
    {
        return (ModuleConf)MemberwiseClone();
    }

    object ICloneable.Clone()
    {
        return MemberwiseClone();
    }
}

public sealed record K20StreamItem(
    string Url,
    string Name,
    string Title,
    string Quality,
    string Format,
    SubtitleTpl Subtitles,
    System.Collections.Generic.List<HeadersModel> Headers
);
